# Generated by Django 2.2.6 on 2019-10-28 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='price',
            field=models.DecimalField(decimal_places=2, default=4.99, max_digits=4, max_length=4),
        ),
        migrations.AlterField(
            model_name='topping',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1.99, max_digits=4, max_length=4),
        ),
    ]
